/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUserDeleteAccountRouteImport } from './routes/api/user/delete-account'
import { Route as ApiInternalAuthUrlsRouteImport } from './routes/api/internal/auth-urls'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserDeleteAccountRoute = ApiUserDeleteAccountRouteImport.update({
  id: '/api/user/delete-account',
  path: '/api/user/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalAuthUrlsRoute = ApiInternalAuthUrlsRouteImport.update({
  id: '/api/internal/auth-urls',
  path: '/api/internal/auth-urls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/auth-urls': typeof ApiInternalAuthUrlsRoute
  '/api/user/delete-account': typeof ApiUserDeleteAccountRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/auth-urls': typeof ApiInternalAuthUrlsRoute
  '/api/user/delete-account': typeof ApiUserDeleteAccountRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/auth-urls': typeof ApiInternalAuthUrlsRoute
  '/api/user/delete-account': typeof ApiUserDeleteAccountRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/auth/$'
    | '/api/internal/auth-urls'
    | '/api/user/delete-account'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/auth/$'
    | '/api/internal/auth-urls'
    | '/api/user/delete-account'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/auth/$'
    | '/api/internal/auth-urls'
    | '/api/user/delete-account'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInternalAuthUrlsRoute: typeof ApiInternalAuthUrlsRoute
  ApiUserDeleteAccountRoute: typeof ApiUserDeleteAccountRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/delete-account': {
      id: '/api/user/delete-account'
      path: '/api/user/delete-account'
      fullPath: '/api/user/delete-account'
      preLoaderRoute: typeof ApiUserDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/auth-urls': {
      id: '/api/internal/auth-urls'
      path: '/api/internal/auth-urls'
      fullPath: '/api/internal/auth-urls'
      preLoaderRoute: typeof ApiInternalAuthUrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInternalAuthUrlsRoute: ApiInternalAuthUrlsRoute,
  ApiUserDeleteAccountRoute: ApiUserDeleteAccountRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
